### ISSUE TITLE
Eigen3 problem?

### ISSUE THREAD

**Issue by yuyuyu00** [robofit/but_velodyne_lib#11]
Dear All,
I managed to compile the but_velodyne_lib. then I run the script "demo.sh" to download 5 datasets.
but i met a problem like this:

> > > collar-lines-odom 000000.bin 000001.bin 000002.bin 000003.bin 000004.bin > estimated.poses
> > > 21509: KITTI file: 000000.bin
> > > Read KTTI point cloud 000000.bin with 124669 points.
> > > collar-lines-odom: /usr/local/include/eigen3/Eigen/src/Core/DenseStorage.h:86: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " ***\* READ THIS WEB PAGE !!! ****"' failed.
> > > 已放弃

it looks like the Eigen library's  align problem,   my Eigen version is 3.20... how can I slover this problem?

**Comment by yuyuyu00** [comment]
i have locat the issue in the following  code in CollarLinesRegistrationPipeline.cpp:

Eigen::Matrix4f CollarLinesRegistrationPipeline::runRegistration(const VelodynePointCloud &target_cloud,
                                              Mat &covariance) {
  PolarGridOfClouds::Ptr target_polar_grid = PolarGridOfClouds::of(target_cloud);
  Eigen::Matrix4f transformation;
  if(!history.empty()) {
    pickBestByAverage(runRegistrationEffective(target_polar_grid),
                      transformation, covariance);
    estimation.addMeassurement(transformation);
  } else {
    transformation = Eigen::Matrix4f::Identity();
    covariance = cv::Mat::zeros(6, 6, CV_64FC1);
  }
  --->updateHistory(target_polar_grid, transform**ation);_
  pose_index++;
  return transformation;
}

**Comment by martin-velas** [comment]
Hi - thanks for the interest in our library and for reporting this issue. I have tried to rebuild the library from scratch using Eigen 3.2.0 and the issue you reported did not occur. 

Unfortunately, from the snippet you posted I can not tell what caused the problem. But I have some hints for you to locate the problem:
- use `gdb` and post here the output of backtrace. Run `gdb ./bin/collar-lines-odom` and execute `run 000000.bin 000001.bin 000002.bin` in the gdb console. After the crash, use `bt` to show the backtrace.
- what platform do you use? In http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html I read that win compilers can cause such problems. 
- try to disable optimal vectorization as described in http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html at the bottom. This may slow down the execution, but at least you can use the library until the more proper solution will be found.

Good luck, Martin.

**Comment by yuyuyu00** [comment]
Thanks for your help,  I disable optimal vectorization as described above by Eigen macro: 'EIGEN_DONT_ALIGN_STATICALLY'.   now it seems worked well.
 my platform is ubuntu 14.04 32bit ,work in a vmware. I think maybe this is the problem...
