### ISSUE TITLE
Does this result Normal?

### ISSUE THREAD

**Issue by yuyuyu00** [robofit/but_velodyne_lib#12]
I've test several times with the script/demo.sh,  this is the best result,but  there is still some errors matching.. Does this result normal?
![Uploading testbutvelodyne_.jpg…]()

**Comment by yuyuyu00** [comment]
![testbutvelodyne_](https://cloud.githubusercontent.com/assets/4252742/17544278/cc18eb6c-5f08-11e6-91bd-0a50c4133cbd.jpg)

**Comment by martin-velas** [comment]
Hello. Hmm - some error will always be presented. I can not tell from this screenshot how significant the error of your estimation is. You can check how the result looks like for odometry estimation run on my computer: [estimated.poses.txt](https://github.com/robofit/but_velodyne_lib/files/410915/estimated.poses.txt). Download this file and run `./bin/show-kitti-poses 000000.bin 000001.bin 000002.bin 000003.bin 000004.bin estimated.poses.txt`. If this result if significantly different from your one, let me know.
Martin.

**Comment by yuyuyu00** [comment]
I test odometry estimation with the scripts : ./bin/collar-lines-odom  000000.bin 000001.bin 000002.bin 000003.bin 000004.bin > estimated.txt ,with no change any parametes..
[estimated.txt](https://github.com/robofit/but_velodyne_lib/files/414517/estimated.txt)
there is a little different from your result.. have you changed some parameters?

**Comment by yuyuyu00** [comment]
thanks ,,   I know the reason..   the wrong result made by a debug version .  I rebuild  a release version, the result looks like good..
[estimated (2).txt](https://github.com/robofit/but_velodyne_lib/files/414539/estimated.2.txt)

**Comment by martin-velas** [comment]
Yes - there are parameters limiting the resources spent for registration - see: `CollarLinesRegistrationPipeline::Parameters`. Since you have built debug version, the code was rather slow and time limit exceeded after small number of iterations.
