### ISSUE TITLE
Error while installing but_velodyne_lib

### ISSUE THREAD

**Issue by anshulpaigwar** [robofit/but_velodyne_lib#15]
when I make the but Velodyne lib I am getting following error: ‘cv:: vector’ has not been declared
I have installed Opencv2.4.13 but still the error persist

```
In file included from /home/nuc/Downloads/but_velodyne_lib-master/include/but_velodyne/CollarLinesRegistration.h:33:0,
                 from /home/nuc/Downloads/but_velodyne_lib-master/src/CollarLinesRegistration.cpp:32:
/home/nuc/Downloads/but_velodyne_lib-master/include/but_velodyne/Visualizer3D.h:256:35: error: ‘cv::vector’ has not been declared
                               cv::vector<cv::DMatch> matches = cv::vector<cv::D
                                   ^
/home/nuc/Downloads/but_velodyne_lib-master/include/but_velodyne/Visualizer3D.h:256:41: error: expected ‘,’ or ‘...’ before ‘<’ token
                               cv::vector<cv::DMatch> matches = cv::vector<cv::D
                                         ^
In file included from /usr/include/eigen3/Eigen/Core:297:0,
                 from /usr/include/eigen3/Eigen/StdVector:14,
                 from /usr/include/pcl-1.7/pcl/common/eigen.h:58,
                 from /home/nuc/Downloads/but_velodyne_lib-master/include/but_velodyne/CollarLinesRegistration.h:28,
                 from /home/nuc/Downloads/but_velodyne_lib-master/src/CollarLinesRegistration.cpp:32:
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h: In instantiation of ‘static void Eigen::PlainObjectBase<Derived>::_check_template_params() [with Derived = Eigen::Matrix<float, 1, -1, 16>]’:
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:508:29:   required from ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 1, -1> >; Derived = Eigen::Matrix<float, 1, -1, 16>]’
/usr/include/eigen3/Eigen/src/Core/Matrix.h:379:29:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 1, -1> >; _Scalar = float; int _Rows = 1; int _Cols = -1; int _Options = 16; int _MaxRows = 1; int _MaxCols = -1]’
/home/nuc/Downloads/but_velodyne_lib-master/src/CollarLinesRegistration.cpp:302:59:   required from here
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:862:7: error: ‘INVALID_MATRIX_TEMPLATE_PARAMETERS’ is not a member of ‘Eigen::internal::static_assertion<false>’
       EIGEN_STATIC_ASSERT((EIGEN_IMPLIES(MaxRowsAtCompileTime==1 && MaxColsAtCo
       ^
CMakeFiles/but_velodyne.dir/build.make:62: recipe for target 'CMakeFiles/but_velodyne.dir/src/CollarLinesRegistration.o' failed
make[2]: *** [CMakeFiles/but_velodyne.dir/src/CollarLinesRegistration.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/but_velodyne.dir/all' failed
make[1]: *** [CMakeFiles/but_velodyne.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by martin-velas** [comment]
Hi! These compatibility issues with different library versions are bit painful.
Try change `cv::vector` to `std::vector`. Moreover regarding second Eigen error in the output above, try this change: https://github.com/martin-velas/but_velodyne_lib/commit/87a1663ef261f53c81ecf7198992d3e26470b89d
Cheers, Martin.

**Comment by deepmeng** [comment]
hello man, I meet the similar error：

[  3%] Building CXX object CMakeFiles/but_velodyne.dir/src/CollarLinesRegistration.o
In file included from /usr/local/include/eigen3/Eigen/Core:347:0,
                 from /usr/local/include/eigen3/Eigen/StdVector:14,
                 from /usr/local/include/pcl-1.8/pcl/common/eigen.h:58,
                 from /home1/liumeng/M-201/but_velodyne_lib/include/but_velodyne/CollarLinesRegistration.h:28,
                 from /home1/liumeng/M-201/but_velodyne_lib/src/CollarLinesRegistration.cpp:32:
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h: In instantiation of ‘static void Eigen::PlainObjectBase<Derived>::_check_template_params() [with Derived = Eigen::Matrix<float, 1, -1, 16>]’:
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:535:30:   required from ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Cw                                   iseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 1, -1> >; Derived = Eigen::Matrix<float, 1, -1, 16>]’
/usr/local/include/eigen3/Eigen/src/Core/Matrix.h:379:29:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::EigenBase<OtherDerived>&) [with OtherDe                                   rived = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 1, -1> >; _Scalar = float; int _Rows = 1; int _Cols = -1; int _Options = 16; int _MaxRows = 1; int _MaxCols                                    = -1]’
/home1/liumeng/M-201/but_velodyne_lib/src/CollarLinesRegistration.cpp:302:59:   required from here
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:899:7: error: ‘INVALID_MATRIX_TEMPLATE_PARAMETERS’ is not a member of ‘Eigen::internal::static_assertion<false>’
       EIGEN_STATIC_ASSERT((EIGEN_IMPLIES(MaxRowsAtCompileTime==1 && MaxColsAtCompileTime!=1, (Options&RowMajor)==RowMajor)
       ^
make[2]: *** [CMakeFiles/but_velodyne.dir/src/CollarLinesRegistration.o] Error 1
make[1]: *** [CMakeFiles/but_velodyne.dir/all] Error 2
make: *** [all] Error 2

Would you like to help me for solving it? @martin-velas

**Comment by martin-velas** [comment]
Hi! Try to build `opencv3` branch instead of `master`. There have been some updated in Eigen and the recent versions causes this problem.
Hope it helps!

**Comment by deepmeng** [comment]
OK!  I will follow your suggest. thanks!

**Comment by youngbo-shim** [comment]
Hi!
I have installed OpenCV 2.4.13, PCL 1.7 and Eigen3.3.4-2 but also meet similar make errors:

In file included from /usr/local/include/eigen3/Eigen/Core:347:0,
                 from /usr/local/include/eigen3/Eigen/StdVector:14,
                 from /usr/include/pcl-1.7/pcl/common/eigen.h:58,
                 from /home/youngbo/lidar_camera_fusion/src/but_velodyne_lib/include/but_velodyne/CollarLinesRegistration.h:28,
                 from /home/youngbo/lidar_camera_fusion/src/but_velodyne_lib/src/CollarLinesRegistration.cpp:32:
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h: In instantiation of ‘static void Eigen::PlainObjectBase<Derived>::_check_template_params() [with Derived = Eigen::Matrix<float, 1, -1, 16>]’:
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:535:29:   required from ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 1, -1> >; Derived = Eigen::Matrix<float, 1, -1, 16>]’
/usr/local/include/eigen3/Eigen/src/Core/Matrix.h:379:29:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 1, -1> >; _Scalar = float; int _Rows = 1; int _Cols = -1; int _Options = 16; int _MaxRows = 1; int _MaxCols = -1]’
/home/youngbo/lidar_camera_fusion/src/but_velodyne_lib/src/CollarLinesRegistration.cpp:302:59:   required from here
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:899:7: error: ‘INVALID_MATRIX_TEMPLATE_PARAMETERS’ is not a member of ‘Eigen::internal::static_assertion<false>’
       EIGEN_STATIC_ASSERT((EIGEN_IMPLIES(MaxRowsAtCompileTime==1 && MaxColsAtCo
       ^
CMakeFiles/but_velodyne.dir/build.make:62: recipe for target 'CMakeFiles/but_velodyne.dir/src/CollarLinesRegistration.o' failed
make[2]: *** [CMakeFiles/but_velodyne.dir/src/CollarLinesRegistration.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/but_velodyne.dir/all' failed
make[1]: *** [CMakeFiles/but_velodyne.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Can you help me for solving it? @martin-velas

**Comment by martin-velas** [comment]
Hi! Since you combine old opencv and new eigen, you need to patch file `src/CollarLinesRegistration.cpp` (line 301) manually  - see: [src/CollarLinesRegistration.cpp#e26f98](https://github.com/robofit/but_velodyne_lib/commit/e26f980c2497cbae689eecaa6eabb2990cfe0a3d#diff-bdb12eb33cbff129ff9bee6cba19e819)

**Comment by Durant35** [comment]
@anshulpaigwar The [branch: opencv3](https://github.com/robofit/but_velodyne_lib/tree/opencv3) built well here, opencv3 version's problem.
this issue could be closed.

**Comment by suhongren** [comment]
Hello sir, I meet the error：
In file included from /home/henry/but_velodyne_lib/include/but_velodyne/CollarLinesRegistrationPipeline.h:43:0,
                 from /home/henry/but_velodyne_lib/src/CollarLinesRegistrationPipeline.cpp:24:
/home/henry/but_velodyne_lib/include/but_velodyne/MoveEstimation.h:162:7: error: ‘KalmanFilter’ in namespace ‘cv’ does not name a type
   cv::KalmanFilter KF;
       ^
CMakeFiles/but_velodyne.dir/build.make:86: recipe for target 'CMakeFiles/but_velodyne.dir/src/CollarLinesRegistrationPipeline.o' failed
make[2]: *** [CMakeFiles/but_velodyne.dir/src/CollarLinesRegistrationPipeline.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/but_velodyne.dir/all' failed
make[1]: *** [CMakeFiles/but_velodyne.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Can you help me for solving it? @martin-velas

**Comment by martin-velas** [comment]
Hi - see instructions from the repository description:

- OpenCV version 2.4.9 (for OpenCV v3 compatibility see branch opencv3)

You need to install opencv. Hope it helps, Martin.
